// LOGIN ACTIONS
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
// USUARIOS ACTIONS
export const GET_ME = "GET_ME";
export const OBTENER_USUARIOS = "OBTENER_USUARIOS";
export const CREAR_USUARIO = "CREAR_USUARIO";
export const SELECCIONAR_USUARIO = "SELECCIONAR_USUARIO";
export const ELIMINAR_USUARIO = "ELIMINAR_USUARIO";
// CATEGORIAS ACTIONS
export const OBTENER_CATEGORIAS = "OBTENER_CATEGORIAS";
export const OBTENER_CATEGORIAS_BARUCH = "OBTENER_CATEGORIAS_BARUCH";
// PRODUCTOS ACTIONS
export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const OBTENER_PRODUCTOS_VENTA = "OBTENER_PRODUCTOS_VENTA";
export const OBTENER_TOTAL_PRODUCTOS = "OBTENER_TOTAL_PRODUCTOS";
export const OBTENER_LISTADO_STOCK = "OBTENER_LISTADO_STOCK";
export const OBTENER_PRODUCTOS_ERROR = "OBTENER_PRODUCTOS_ERROR";
export const CREAR_PRODUCTO = "CREAR_PRODUCTO";
export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const ELIMINAR_STOCK = "ELIMINAR_STOCK";
export const OBTENER_REPORTE_PRODUCTOS = "OBTENER_REPORTE_PRODUCTOS";
export const OBTENER_REPORTE_STOCK = "OBTENER_REPORTE_STOCK";
// PRODUCTOS BARUCH ACTIONS
export const OBTENER_PRODUCTOS_BARUCH = "OBTENER_PRODUCTOS_BARUCH";
export const OBTENER_PRODUCTOS_BARUCH_VENTA = "OBTENER_PRODUCTOS_BARUCH_VENTA";
export const OBTENER_TOTAL_PRODUCTOS_BARUCH = "OBTENER_TOTAL_PRODUCTOS_BARUCH";
export const OBTENER_LISTADO_STOCK_BARUCH = "OBTENER_LISTADO_STOCK_BARUCH";
export const OBTENER_PRODUCTOS_ERROR_BARUCH = "OBTENER_PRODUCTOS_ERROR_BARUCH";
export const CREAR_PRODUCTO_BARUCH = "CREAR_PRODUCTO_BARUCH";
export const EDITAR_PRODUCTO_BARUCH = "EDITAR_PRODUCTO_BARUCH";
export const ELIMINAR_PRODUCTO_BARUCH = "ELIMINAR_PRODUCTO_BARUCH";
export const ELIMINAR_STOCK_BARUCH = "ELIMINAR_STOCK_BARUCH";
export const OBTENER_REPORTE_PRODUCTOS_BARUCH = "OBTENER_REPORTE_PRODUCTOS_BARUCH";
export const OBTENER_REPORTE_STOCK_BARUCH = "OBTENER_REPORTE_STOCK_BARUCH";
// VENTAS ACTIONS
export const SELECCIONAR_VENTA = "SELECCIONAR_VENTA";
export const SELECCIONAR_VENTA_CANCELADA = "SELECCIONAR_VENTA_CANCELADA";
export const OBTENER_TOTAL_VENTAS = "OBTENER_TOTAL_VENTAS";
export const OBTENER_VENTAS = "OBTENER_VENTAS";
export const OBTENER_LISTADO_VENTAS_HOY = "OBTENER_LISTADO_VENTAS_HOY";
export const OBTENER_VENTAS_HOY = "OBTENER_VENTAS_HOY";
export const OBTENER_VENTAS_ENCABEZADO_HOY = "OBTENER_VENTAS_ENCABEZADO_HOY";
export const OBTENER_VENTAS_GANANCIAS = "OBTENER_VENTAS_GANANCIAS";
export const OBTENER_VENTAS_USUARIOS = "OBTENER_VENTAS_USUARIOS";
export const OBTENER_REPORTE_VENTAS = "OBTENER_REPORTE_VENTAS";
export const OBTENER_REPORTE_VENTAS_CATEGORIA = "OBTENER_REPORTE_VENTAS_CATEGORIA";
export const OBTENER_VENTAS_CANCELADAS = "OBTENER_VENTAS_CANCELADAS";
export const OBTENER_VENTAS_ERROR = "OBTENER_VENTAS_ERROR";
export const AGREGAR_PRODUCTO_CARRITO = "AGREGAR_PRODUCTO_CARRITO";
export const AGREGAR_PRODUCTOS_CARRITO = "AGREGAR_PRODUCTOS_CARRITO";
export const ELIMINAR_PRODUCTO_CARRITO = "ELIMINAR_PRODUCTO_CARRITO";
export const ELIMINAR_REPORTE_VENTAS = "ELIMINAR_REPORTE_VENTAS";
export const AGREGAR_PRODUCTO_CANTIDAD = "AGREGAR_PRODUCTO_CANTIDAD";
export const RESTAR_PRODUCTO_CANTIDAD = "RESTAR_PRODUCTO_CANTIDAD";
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const VENTA_REALIZADA = "VENTA_REALIZADA";
export const CAMBIO_TOTAL_VENTA = "CAMBIO_TOTAL_VENTA";
export const OBTENER_TOTAL_INVERTIDO = "OBTENER_TOTAL_INVERTIDO";
export const REPORTE_VENTA_PRODUCTOS = "REPORTE_VENTA_PRODUCTOS";
// VENTAS ACTIONS BARUCH
export const SELECCIONAR_VENTA_BARUCH = "SELECCIONAR_VENTA_BARUCH";
export const SELECCIONAR_VENTA_CANCELADA_BARUCH = "SELECCIONAR_VENTA_CANCELADA_BARUCH";
export const OBTENER_TOTAL_VENTAS_BARUCH = "OBTENER_TOTAL_VENTAS_BARUCH";
export const OBTENER_VENTAS_BARUCH = "OBTENER_VENTAS_BARUCH";
export const OBTENER_LISTADO_VENTAS_HOY_BARUCH = "OBTENER_LISTADO_VENTAS_HOY_BARUCH";
export const OBTENER_VENTAS_HOY_BARUCH = "OBTENER_VENTAS_HOY_BARUCH";
export const OBTENER_VENTAS_ENCABEZADO_HOY_BARUCH = "OBTENER_VENTAS_ENCABEZADO_HOY_BARUCH";
export const OBTENER_VENTAS_GANANCIAS_BARUCH = "OBTENER_VENTAS_GANANCIAS_BARUCH";
export const OBTENER_VENTAS_USUARIOS_BARUCH = "OBTENER_VENTAS_USUARIOS_BARUCH";
export const OBTENER_REPORTE_VENTAS_BARUCH = "OBTENER_REPORTE_VENTAS_BARUCH";
export const OBTENER_REPORTE_VENTAS_CATEGORIA_BARUCH = "OBTENER_REPORTE_VENTAS_CATEGORIA_BARUCH";
export const OBTENER_VENTAS_CANCELADAS_BARUCH = "OBTENER_VENTAS_CANCELADAS_BARUCH";
export const OBTENER_VENTAS_ERROR_BARUCH = "OBTENER_VENTAS_ERROR_BARUCH";
export const AGREGAR_PRODUCTO_CARRITO_BARUCH = "AGREGAR_PRODUCTO_CARRITO_BARUCH";
export const AGREGAR_PRODUCTOS_CARRITO_BARUCH = "AGREGAR_PRODUCTOS_CARRITO_BARUCH";
export const ELIMINAR_PRODUCTO_CARRITO_BARUCH = "ELIMINAR_PRODUCTO_CARRITO_BARUCH";
export const ELIMINAR_REPORTE_VENTAS_BARUCH = "ELIMINAR_REPORTE_VENTAS_BARUCH";
export const AGREGAR_PRODUCTO_CANTIDAD_BARUCH = "AGREGAR_PRODUCTO_CANTIDAD_BARUCH";
export const RESTAR_PRODUCTO_CANTIDAD_BARUCH = "RESTAR_PRODUCTO_CANTIDAD_BARUCH";
export const SELECTED_PRODUCT_BARUCH = "SELECTED_PRODUCT_BARUCH";
export const VENTA_REALIZADA_BARUCH = "VENTA_REALIZADA_BARUCH";
export const CAMBIO_TOTAL_VENTA_BARUCH = "CAMBIO_TOTAL_VENTA_BARUCH";
export const OBTENER_TOTAL_INVERTIDO_BARUCH = "OBTENER_TOTAL_INVERTIDO_BARUCH";
export const REPORTE_VENTA_PRODUCTOS_BARUCH = "REPORTE_VENTA_PRODUCTOS_BARUCH";
// CAJA ACTIONS
export const OBTENER_CAJAS_GENERAL = "OBTENER_CAJAS_GENERAL";
export const OBTENER_CAJAS_GENERAL_ERROR = "OBTENER_CAJAS_GENERAL_ERROR";
export const ABRIR_CAJA = "ABRIR_CAJA";
export const OBTENER_CAJA = "OBTENER_CAJA";
export const OBTENER_CAJA_ERROR = "OBTENER_CAJA_ERROR";
// CAJA ACTIONS BARUCH
export const OBTENER_CAJAS_GENERAL_BARUCH = "OBTENER_CAJAS_GENERAL_BARUCH";
export const OBTENER_CAJAS_GENERAL_ERROR_BARUCH = "OBTENER_CAJAS_GENERAL_ERROR_BARUCH";
export const ABRIR_CAJA_BARUCH = "ABRIR_CAJA_BARUCH";
export const OBTENER_CAJA_BARUCH = "OBTENER_CAJA_BARUCH";
export const OBTENER_CAJA_ERROR_BARUCH = "OBTENER_CAJA_ERROR_BARUCH";

export const CLEAR_AUTENTICACION = "CLEAR_AUTENTICACION";
export const CLEAR_USUARIOS = "CLEAR_USUARIOS";
export const CLEAR_PRODUCTOS = "CLEAR_PRODUCTOS";
export const CLEAR_CATEGORIAS = "CLEAR_CATEGORIAS";
export const CLEAR_VENTAS = "CLEAR_VENTAS";
export const CLEAR_CAJAS = "CLEAR_CAJAS";
export const CLEAR_LISTADOS_VENTAS = "CLEAR_LISTADOS_VENTAS";


// TIENDAS
export const OBTENER_TIENDAS = "OBTENER_TIENDAS";
export const SELECT_TIENDA = "SELECT_TIENDA";